/**
 * BoletimPage — geração e exibição de boletim técnico de queimadas.
 */

import { useState } from 'react'
import { FileText, Download, Loader2 } from 'lucide-react'
import { getBoletim } from '../services/api'
import { format } from 'date-fns'
import { enUS } from 'date-fns/locale'

interface BoletimData {
  boletim: string
  total_eventos: number
  total_alertas: number
}

export default function BoletimPage() {
  const [boletim, setBoletim] = useState<BoletimData | null>(null)
  const [carregando, setCarregando] = useState(false)
  const [erro, setErro] = useState<string | null>(null)
  const [municipio, setMunicipio] = useState('')

  const gerar = async () => {
    setCarregando(true)
    setErro(null)
    try {
      const dados = await getBoletim(municipio || undefined)
      setBoletim(dados)
    } catch {
      setErro('Failed to generate bulletin. Check the server connection.')
    } finally {
      setCarregando(false)
    }
  }

  const baixar = () => {
    if (!boletim) return
    const blob = new Blob([boletim.boletim], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `boletim-queimadas-ceara-${format(new Date(), 'yyyyMMdd-HHmm')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-4 lg:p-6 space-y-4 max-w-4xl mx-auto">
      <div className="flex items-center gap-2">
        <FileText size={20} className="text-fire-600" aria-hidden="true" />
        <div>
          <h1 className="text-lg font-bold text-slate-900">Technical Bulletin</h1>
          <p className="text-sm text-slate-500">Report generated by the LangGraph agent</p>
        </div>
      </div>

      {/* Controles */}
      <div className="card space-y-3">
        <div className="flex gap-3 flex-wrap">
          <input
            type="text"
            value={municipio}
            onChange={(e) => setMunicipio(e.target.value)}
            placeholder="Specific municipality (optional)"
            className="flex-1 min-w-48 bg-slate-100 border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 placeholder-slate-400 focus:outline-none focus:border-orange-500"
            aria-label="Filter bulletin by municipality"
          />
          <button
            onClick={gerar}
            disabled={carregando}
            className="flex items-center gap-2 px-4 py-2 bg-orange-600 hover:bg-orange-500 disabled:bg-slate-200 text-white rounded-lg text-sm font-medium transition-colors"
          >
            {carregando ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileText size={16} />
                Generate Bulletin
              </>
            )}
          </button>
          {boletim && (
            <button
              onClick={baixar}
              className="btn-ghost"
              aria-label="Download bulletin as text file"
            >
              <Download size={16} />
              Download
            </button>
          )}
        </div>

        {erro && (
          <p className="text-sm text-red-600" role="alert">{erro}</p>
        )}
      </div>

      {/* Boletim */}
      {boletim && (
        <div className="space-y-3">
          {/* Resumo */}
          <div className="grid grid-cols-2 gap-3">
            <div className="card text-center">
              <p className="text-2xl font-bold text-fire-600">{boletim.total_eventos}</p>
              <p className="text-xs text-slate-500">Events detected</p>
            </div>
            <div className="card text-center">
              <p className="text-2xl font-bold text-red-600">{boletim.total_alertas}</p>
              <p className="text-xs text-slate-500">Alerts issued</p>
            </div>
          </div>

          {/* Texto do boletim */}
          <div className="card">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-sm font-semibold text-slate-900">Bulletin Content</h2>
              <span className="text-xs text-slate-500">
                Generated on {format(new Date(), "MM/dd/yyyy 'at' HH:mm", { locale: enUS })}
              </span>
            </div>
            <pre className="text-sm text-slate-600 whitespace-pre-wrap font-mono leading-relaxed bg-stone-50 rounded-lg p-4 overflow-auto max-h-[60vh]">
              {boletim.boletim}
            </pre>
          </div>
        </div>
      )}

      {!boletim && !carregando && (
        <div className="text-center py-16 text-slate-500">
          <FileText size={48} className="mx-auto mb-3 opacity-30" aria-hidden="true" />
          <p>Click &quot;Generate Bulletin&quot; to create the technical report</p>
          <p className="text-sm mt-1">The LangGraph agent will collect and analyze data in real time</p>
        </div>
      )}
    </div>
  )
}
